spring:
  application:
    name: Reddit-Clone
  profiles:
    active: dev

logging:
  level:
    ROOT: INFO
    ORG.TAKER.REDDIT: INFO

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
    session:
      cookie:
        http-only: true
jwt:
  expiration:
    #    time: 900000
    time: 60000